### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by mokerhamer** [umehkg/spgame#6]
Dear Umehkg,

I would like to join the development of Sp-Game. i just need to get in contact with you for startup information. Please contact me at muniersaliba@hotmail.com.

**Comment by globeriz** [comment]
Hello there!

I have sent you a response through your email.

Cheers

**Comment by umehkg** [comment]
Hello there!

I have sent you a response through your email.

Cheers

**Comment by mokerhamer** [comment]
I have responded back :)

**Comment by mokerhamer** [comment]
umehkg ,
Can you provide us with all needed software and information? If you update this github we will fork it.
Besides that is there an existing community that is currently developing SP server?
